spring.application.name=Lombok
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
#spring.data.mongodb.username=myusername
#spring.data.mongodb.password=mypassword
spring.data.mongodb.auto-index-creation=true


