spring.application.name=mongoDB

# Using connection URI
# spring.data.mongodb.uri=mongodb://localhost:27017/spring_boot_tutorial
# with username and password: mongodb://username:password@localhost:27017/spring_boot_tutorial

# Using connection credentials
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=spring_boot_tutorial
# spring.data.mongodb.username=<username>
# spring.data.mongodb.password=<password>