spring.application.name=service-registry

# Default Eureka Server
server.port=8761
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka Server Health Check Configuration
eureka.server.health-check-url-path=/actuator/health
