spring.application.name=Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-r1we13l4hngyja8o.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://myapi.example.com